// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Prediction input format for Image Classification.
public struct ImageClassificationPredictionInstance: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// The image bytes or Cloud Storage URI to make the prediction on.
  public var content: Swift.String = Swift.String()

  /// The MIME type of the content of the image. Only the images in below listed
  /// MIME types are supported.
  /// - image/jpeg
  /// - image/gif
  /// - image/png
  /// - image/webp
  /// - image/bmp
  /// - image/tiff
  /// - image/vnd.microsoft.icon
  public var mimeType: Swift.String = Swift.String()

  /// Initialize a new instance of `ImageClassificationPredictionInstance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageClassificationPredictionInstance().with { $0.content = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.predict.instance.ImageClassificationPredictionInstance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
