// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Prediction input format for Video Object Tracking.
public struct VideoObjectTrackingPredictionInstance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The Google Cloud Storage location of the video on which to perform the
  /// prediction.
  public var content: Swift.String = Swift.String()

  /// The MIME type of the content of the video. Only the following are
  /// supported: video/mp4 video/avi video/quicktime
  public var mimeType: Swift.String = Swift.String()

  /// The beginning, inclusive, of the video's time segment on which to perform
  /// the prediction. Expressed as a number of seconds as measured from the
  /// start of the video, with "s" appended at the end. Fractions are allowed,
  /// up to a microsecond precision.
  public var timeSegmentStart: Swift.String = Swift.String()

  /// The end, exclusive, of the video's time segment on which to perform
  /// the prediction. Expressed as a number of seconds as measured from the
  /// start of the video, with "s" appended at the end. Fractions are allowed,
  /// up to a microsecond precision, and "inf" or "Infinity" is allowed, which
  /// means the end of the video.
  public var timeSegmentEnd: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VideoObjectTrackingPredictionInstance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoObjectTrackingPredictionInstance().with { $0.content = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let content = CodingKeys(stringValue: "content")
    static let mimeType = CodingKeys(stringValue: "mimeType")
    static let timeSegmentStart = CodingKeys(stringValue: "timeSegmentStart")
    static let timeSegmentEnd = CodingKeys(stringValue: "timeSegmentEnd")

    static let _knownKeys: Set<Swift.String> = [
      "content",
      "mimeType",
      "timeSegmentStart",
      "timeSegmentEnd",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .content) {
      self.content = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mimeType) {
      self.mimeType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timeSegmentStart) {
      self.timeSegmentStart = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timeSegmentEnd) {
      self.timeSegmentEnd = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.content, forKey: .content)
    try container.encode(self.mimeType, forKey: .mimeType)
    try container.encode(self.timeSegmentStart, forKey: .timeSegmentStart)
    try container.encode(self.timeSegmentEnd, forKey: .timeSegmentEnd)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.predict.instance.VideoObjectTrackingPredictionInstance"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
