// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Prediction input format for Video Object Tracking.
public struct VideoObjectTrackingPredictionInstance: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// The Google Cloud Storage location of the video on which to perform the
  /// prediction.
  public var content: Swift.String = Swift.String()

  /// The MIME type of the content of the video. Only the following are
  /// supported: video/mp4 video/avi video/quicktime
  public var mimeType: Swift.String = Swift.String()

  /// The beginning, inclusive, of the video's time segment on which to perform
  /// the prediction. Expressed as a number of seconds as measured from the
  /// start of the video, with "s" appended at the end. Fractions are allowed,
  /// up to a microsecond precision.
  public var timeSegmentStart: Swift.String = Swift.String()

  /// The end, exclusive, of the video's time segment on which to perform
  /// the prediction. Expressed as a number of seconds as measured from the
  /// start of the video, with "s" appended at the end. Fractions are allowed,
  /// up to a microsecond precision, and "inf" or "Infinity" is allowed, which
  /// means the end of the video.
  public var timeSegmentEnd: Swift.String = Swift.String()

  /// Initialize a new instance of `VideoObjectTrackingPredictionInstance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoObjectTrackingPredictionInstance().with { $0.content = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.predict.instance.VideoObjectTrackingPredictionInstance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
